version: "3"

services:
  app-server:
    build:
      context: polling-app-server 
      dockerfile: DockerFile
    ports:
      - "8082:8082"
    restart: always
    networks: 
      - backend
      - frontend

  app-client:
    build:
      context: polling-app-client
      dockerfile: DockerFile
    ports:
      - "3000:3000" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

 
